version: 2
updates:
  - package-ecosystem: terraform
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly

  - package-ecosystem: github-actions
    assignees:
      - stfsy
    directory: /
    schedule:
      interval: monthly
